// Generated by CoffeeScript 1.3.3
(function() {
  var $, folderRead, fs, path, readFile;

  fs = require('fs');

  $ = require('jquery');

  path = 'data/wiki/';

  folderRead = function(err, files) {
    var file, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      if (file.indexOf('ephttp') === 0) {
        readFile(file);
      }
      break;
    }
    return _results;
  };

  readFile = function(file) {
    return fs.readFile(path + file, 'utf8', function(err, data) {
      var $f, $infobox, title, titleBoxes;
      $f = $(data);
      $infobox = $f.find('.infobox');
      titleBoxes = $infobox.find('.navbox-title');
      title = $(titleBoxes[0]).text();
      return console.log(title);
    });
  };

  fs.readdir(path, folderRead);

}).call(this);
