// Generated by CoffeeScript 1.3.3
(function() {
  var episodeList, episodesLoaded, episodesToLoad, filename, fs, http, loadEpisode, url;

  http = require('http');

  fs = require('fs');

  url = require('url');

  filename = 'data/epList.json';

  episodeList = [];

  fs.readFile(filename, 'utf8', function(err, d) {
    var list;
    list = JSON.parse(d);
    episodeList = list.result;
    return loadEpisode();
  });

  loadEpisode = function() {
    var episode, rdf;
    episode = episodeList[episodesLoaded];
    rdf = "http://rdf.freebase.com/rdf" + episode.id;
    console.log(url.parse(rdf));
    return http.request(url.parse(rdf), function(response) {
      var str;
      str = "";
      response.on("data", function(data) {
        str += data;
        return console.log(data);
      });
      response.on("end", function() {
        fs.writeFile("data/freebase/ep" + episodesLoaded + ".xml", str);
        episodesLoaded++;
        return loadEpisode();
      });
    }).end();
  };

  episodesLoaded = 0;

  episodesToLoad = episodeList.length;

}).call(this);
