// Generated by CoffeeScript 1.3.3
var allLinesRead, db, dbConnected, fs, lines, linesRead, pg, ratings, ratingsFileRead, readLine, seinfeldLines;

fs = require('fs');

pg = require('pg');

ratings = null;

ratingsFileRead = function(err, data) {
  ratings = data;
  return pg.connect(process.env.HEROKU_POSTGRESQL_PURPLE_URL, dbConnected);
};

db = null;

lines = [];

dbConnected = function(err, client) {
  db = client;
  lines = ratings.split("\n");
  return readLine();
};

linesRead = 0;

seinfeldLines = "";

readLine = function() {
  var add, line;
  line = lines[linesRead];
  if (typeof line === 'undefined') {
    allLinesRead();
    return;
  }
  if (line.indexOf('"Seinfeld"') !== -1 || line.indexOf("Seinfeld Chronicle") !== -1) {
    add = line + "\n";
    if (line.indexOf('The Chronicle') !== -1) {
      add = line.replace('The Chronicle', 'The Clip Show (Part 1)') + "\n";
      add += line.replace('The Chronicle', 'The Clip Show (Part 2)') + "\n";
    }
    seinfeldLines += add;
  }
  linesRead++;
  return setTimeout(readLine, 1);
};

allLinesRead = function() {
  return fs.writeFile('data/imdb/seinfeldRatings', seinfeldLines, 'utf8', function() {
    console.log('done');
    return process.exit();
  });
};

fs.readFile('data/imdb/ratings.list', 'utf8', ratingsFileRead);
